name: 'Get Repo Version'
description: 'Retrieve the Package Version number'
outputs:
  package_version:
    description: 'The package version'
    value: ${{ steps.get-version-number.outputs.PKG_VER }}
runs:
  using: "composite"
  steps:
    - id: get-version-number
      run: echo ::set-output name=PKG_VER::$(Rscript -e "cat(read.dcf('DESCRIPTION')[, 'Version'])")
      shell: bash
