name: 'Get Repo Version'
description: 'Retrieve the Package Version number'
inputs:
  github_slug:
    description: 'The repository slug'
    required: true
outputs:
  repo_version:
    description: 'The package version'
    value: ${{ steps.get-version-number.outputs.PKG_VER }}
runs:
  using: 'composite'
  steps:
    - id: get-version-number
        run: echo "::set-output name=PKG_VER::$(echo $RANDOM)"
        shell: bash
