name: 'Install windows System Dependencies'
description: 'Install a comprehensive list of system dependencies'
runs:
  using: "composite"
  steps:
    - name: Install System Dependencies (windows)
      run: ${GITHUB_ACTION_PATH}/pacman.sh
      shell: msys2 {0}