name: 'Install windows System Dependencies'
description: 'Install a comprehensive list of system dependencies'
runs:
  using: "composite"
  steps:
    - name: Install System Dependencies (windows)
      run: ${GITHUB_ACTION_PATH}/pacman.sh
      shell: msys2 {0}
    - name: Install JAGS
      run: |
        curl.exe -o JAGS-4.2.0-Rtools33.exe -L https://github.com/muschellij2/neuroc_dependencies/raw/master/JAGS-4.2.0-Rtools33.exe
        D:\a\actions\actions\JAGS-4.2.0-Rtools33.exe /S
      shell: cmd 