name: 'Uploads Code Coverage to Coveralls'
description: 'Enable repo, retrieve repo_token and upload coverage to coveralls.io'
runs:
  using: "composite"
  steps:
    - uses: octokit/request-action@v2.x
      id: get_json
      with:
        route: GET https://coveralls.io/github/lemurheavy/coveralls-ruby.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: ${{ steps.get_json.outputs.data }}"