sudo apt-get install -y cmake ;    
sudo apt-get install -y libssh-dev;
sudo apt-get install -y jags
sudo apt-get install -y libv8-dev;
sudo apt-get install -y libfftw3-dev ;
sudo apt-get install -y dcmtk ;
sudo apt-get install -y libsecret-1-dev ;
sudo apt-get install -y libpng-dev ;
sudo apt-get install -y libpoppler-cpp-dev ;
sudo apt-get install -y libhdf5-dev ;
sudo apt-get install -y mesa-common-dev libglu1-mesa-dev ;
sudo apt-get install -y libprotobuf-dev protobuf-compiler libprotoc-dev ;
sudo apt-get install -y ffmpeg --allow-unauthenticated ;
sudo apt-get install -y libmagick++-dev ;
sudo apt-get install -y ghostscript imagemagick
sudo apt-get install -y libudunits2-dev ;
sudo apt-get install -y libjq-dev ;
sudo apt-get install -y libmng2 ; 
sudo apt-get install -y libapparmor-dev ;
sudo apt-get install -y imagej ;
sudo apt-get install -y bowtie2 ;
sudo apt-get install -y libgit2-dev ;
sudo apt-get install -y libtiff-dev ;
sudo apt-get install -y unixodbc-dev ;
sudo apt-get install -y libsodium-dev ;
sudo apt-get install -y libtesseract-dev libleptonica-dev tesseract-ocr-eng ;
sudo apt-get install -y wget ;
sudo apt-get install -y libzmq3-dev ;
sudo apt-get install -y libwebp-dev ;
sudo apt-get install -y cargo ;
sudo apt-get install -y qgis ;
sudo apt-get install -y libharfbuzz-dev libfribidi-dev ;
sudo apt-get install -y tk-dev ;
sudo apt-get install -y tidy ;
sudo apt-get install -y libcurl4-openssl-dev ;
sudo apt-get install -y libv8-dev ;
sudo apt-get install -y python3-h5py ;
sudo apt-get install -y cython3 ;
