on: [push]

jobs:
  get_repo_version_job:
    runs-on: ${{ matrix.config.os }}
    if: "contains(github.event.head_commit.message, 'coveralls')"
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-16.04,   r: 'release', r_ver: '4.0'}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_json
        with:
          route: GET https://coveralls.io/github/lemurheavy/coveralls-ruby.json

      - run: "echo latest release: ${{ steps.get_json.outputs.data }}"