on: [push]

jobs:
  get_repo_version_job:
    runs-on: ${{ matrix.config.os }}
    if: "contains(github.event.head_commit.message, 'coveralls')"
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-16.04,   r: 'release', r_ver: '4.0'}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    steps:
      - name: Enable Repo on Coveralls
        id: enable_coveralls
        run: |
          curl -s -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: token $COVERALLS_TOKEN" \
            -d '{"repo": {"service": "github","name": "adigherman/actions"}}' \
            -X POST https://coveralls.io/api/repos
      - name: Get Repo Token
        id: get_coverall_repo_token
        run: |
          echo ::set-env name=COVERALLS_REPO_TOKEN::(curl -s -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: token $COVERALLS_TOKEN" \
            https://coveralls.io/api/repos/github/adigherman/actions \
            | jq '.token')
      - name: Print repo Token
        run: echo "REPO TOKEN IS COVERALLS_REPO_TOKEN"