on: [push]

jobs:
  get_repo_version_job:
    runs-on: ${{ matrix.config.os }}
    if: "contains(github.event.head_commit.message, 'coveralls')"
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-16.04,   r: 'release', r_ver: '4.0'}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    steps:
      - name: Enable Coveralls repo
        uses: octokit/request-action@v2.x
        id: enable_coveralls
        with:
          route: POST https://coveralls.io/api/repos/github/adigherman/actions
        
      - run: "echo latest release: ${{ steps.enable_coveralls.outputs.data }}"