on: [push]

jobs:
  get_repo_version_job:
    runs-on: ${{ matrix.config.os }}
    if: "contains(github.event.head_commit.message, 'coveralls')"
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-16.04,   r: 'release', r_ver: '4.0'}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    steps:
    
      - name: Enable Coveralls repo
        id: enable_coveralls
        run: |
          curl -i -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: token $COVERALLS_TOKEN" \
            -d '{"repo": {"service": "github","name": "adigherman/actions"}}' \
            -X POST https://coveralls.io/api/repos