on: [push]

jobs:
  get_repo_version_job:
    runs-on: ${{ matrix.config.os }}
    if: "contains(github.event.head_commit.message, 'coveralls')"
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-16.04,   r: 'release', r_ver: '4.0'}
    steps:
      - name: Get Coveralls API
        uses: adigherman/actions/coveralls@master
        id: get-coveralls