on: [push]

jobs:
  create_release:
    name: Create test release
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'delete-release-by-tag')"
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::'1.0.test'

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag_name.outputs.VERSION }}
          release_name: Release ${{ steps.get_tag_name.outputs.VERSION }}
          draft: false
          prerelease: false

  delete_release_by_tag:
    needs: create_release
    name: Delete Release by Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Delete Release
        uses: adigherman/actions/delete-release-by-tag@master
        id: delete-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          tag: '1.0.test'