on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Get repo name
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get repo name
        uses: adigherman/actions/get-repo-name@v1
        id: get-name
        with:
          github_slug: ${{ github.repository }}
      - name: Echo repo name
        run: echo "Repo name is ${{ steps.get-name.outputs.repo_name }}"
