on: [push]

jobs:
  install_sysdeps_job:
    runs-on: ${{ matrix.config.os }}
    if: "contains(github.event.head_commit.message, 'install-sysdeps-windows')"
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest,   r: 'release', r_ver: '4.0'}
    steps:
      - name: Install JAGS
        run: |
          curl.exe -o wjags.exe https://github.com/muschellij2/neuroc_dependencies/raw/master/JAGS-4.2.0-Rtools33.exe
          dir
          wjags.exe /S
          del wjags.exe
