on: [push]

jobs:
  install_sysdeps_job:
    runs-on: ${{ matrix.config.os }}
    if: "contains(github.event.head_commit.message, 'install-sysdeps-windows')"
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest,   r: 'release', r_ver: '4.0'}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain
      - name: Install JAGS
        run: |
          curl.exe -o wjags.exe --url https://github.com/adigherman/actions/raw/master/files/JAGS-4.3.0.exe
          JAGS-4.3.0.exe /S
          del JAGS-4.3.0.exe
        shell: cmd 