on: [push]

jobs:
  install_sysdeps_job:
    runs-on: ${{ matrix.config.os }}
    if: "contains(github.event.head_commit.message, 'install-sysdeps-windows')"
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest,   r: 'release', r_ver: '4.0'}
    steps:
      - name: Get release asset info
        uses: adigherman/actions/install-sysdeps-windows@master
        id: install-sysdeps-windows