on: [push]

jobs:
  install_sysdeps_job:
    runs-on: ${{ matrix.config.os }}
    if: "contains(github.event.head_commit.message, 'install-sysdeps-windows')"
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest,   r: 'release', r_ver: '4.0'}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain
      - name: Install System Dependencies
        uses: adigherman/actions/install-sysdeps-windows@master
        id: install-sysdeps-windows
      - name: Install JAGS
        run: |
          curl.exe -o wjags.exe --url https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.0.exe/download
          wjags.exe /S
          del wjags.exe
        shell: cmd 