on: [push]

jobs:
  install_sysdeps_job:
    runs-on: ${{ matrix.config.os }}
    if: "contains(github.event.head_commit.message, 'install-sysdeps-linux')"
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04,   r: 'release', r_ver: '4.0'}
    steps:
      - name: Install System Dependencies
        uses: adigherman/actions/install-sysdeps-linux@master
        id: install-sysdeps-linux